Add more information about golang materials
Metaboros/Languages pull request #11
Opened 2022-02-10 11:51 UTC by samurai-of-honor

2022-02-10 15:46 UTC, samurai-of-honor commented
Which version is better? All on one line or starting from a new one?

2022-02-11 06:18 UTC, samurai-of-honor commented
Which version is better? All in one column or on a new line?

2022-02-11 08:22 UTC, SergeyOcheretenko requested changes

2022-02-11 08:22 UTC, SergeyOcheretenko commented on Go/README.md
> +<b>Отсутствует</b> возможность ввода при работе програмы <b>но есть интересные примеры кода.</b>
Add , before "но" please

2022-02-11 08:23 UTC, SergeyOcheretenko commented
Try to delete <br> tags and use markdown spacing

2022-02-11 08:59 UTC, SergeyOcheretenko approved these changes

2022-02-11 09:00 UTC, merged