add Golang stepik course and browser IDE
Metaboros/Languages pull request #4
Opened 2022-02-03 11:56 UTC by samurai-of-honor

2022-02-03 17:35 UTC, SergeyOcheretenko requested changes

2022-02-03 17:35 UTC, SergeyOcheretenko commented on README.md
> +## JavaScript
Change all title to ### mode, it's more beautiful and easy for eyes

2022-02-03 17:35 UTC, SergeyOcheretenko commented on README.md
> +## Python
Change all title to ### mode, it's more beautiful and easy for eyes

2022-02-03 17:35 UTC, SergeyOcheretenko commented on README.md
> +## C#.
Change all title to ### mode, it's more beautiful and easy for eyes

2022-02-03 17:35 UTC, SergeyOcheretenko commented on README.md
> +## Java
Change all title to ### mode, it's more beautiful and easy for eyes

2022-02-03 17:39 UTC, SergeyOcheretenko requested changes

2022-02-03 17:39 UTC, SergeyOcheretenko commented on README.md
> +## C#.
Delete dot near C#

2022-02-03 17:39 UTC, SergeyOcheretenko commented on README.md
> ++ [Stepik](./Go/README.md#stepik)
Change "Stepik" to "Stepik Courses"

2022-02-03 17:46 UTC, samurai-of-honor commented on README.md
> +## C#.
If i delete dot - # will not be displayed. What should I do?

2022-02-03 17:48 UTC, SergeyOcheretenko commented on README.md
> +## C#.
Add backslash before #:
C\#

2022-02-03 17:52 UTC, samurai-of-honor commented on README.md
> +## C#.
My mistake. For some reason it didn't work in my editor

2022-02-04 15:48 UTC, SergeyOcheretenko approved these changes

2022-02-04 15:48 UTC, merged