add online js editors and navigation in main readme
Metaboros/Languages pull request #6
Opened 2022-02-04 22:12 UTC by samurai-of-honor

2022-02-05 09:18 UTC, SergeyOcheretenko requested changes

2022-02-05 09:18 UTC, SergeyOcheretenko commented on JavaScript/README.md
> +### Online Editors<a name="online-editors"></a>
Add replit.com in Online Editors

2022-02-05 10:36 UTC, samurai-of-honor commented
Done

2022-02-08 07:56 UTC, SergeyOcheretenko approved these changes

2022-02-08 07:56 UTC, merged